### PR TITLE
Add canonical and acceptable answers to the hunt definition, and add a REST route to fetch them

### PR DESCRIPTION
**Pull request by obijywk**
fixes eastern-toys/Cube#15

### CODE REVIEW

**Comment by tkfocht** [comment]
If there are multiple answers for a puzzle, this doesn't allow the service to return just the ones that have been solved without revealing the others. I don't think we have to worry about that in detail yet, but the all-or-nothing approach is going to cause problems down the line. (Looking through the code as it stands, I would anticipate that we would use VisibilityStatus to encode which answers have been solved - this is part of the intent in VisibilityStatus not being enumerated.)

I'm also uncomfortable with the way Answer took over the slot in the model that was more about Puzzle. I'm wondering if we ought to make Puzzle or Solvable a full-fledged model object that has some minimal amount of metadata - like name? As we move past the LinearExample, the ability to extend Solvable into Round and Puzzle and define the links between them for a HuntDefinition will probably help us ensure we do the workflow transitions correctly.

**Comment by obijywk** [comment]
All good points, I agree with all of that.

I think we have two different use cases that require returning answers:
1. In the call queue, displaying all canonical and acceptable answers for a puzzle, so folks manning the phones know what's correct.
2. In the solving team webapp, displaying the subset of canonical answers that team has already gotten correct for each puzzle.

These two cases feel different to me, because (2) is associated with a specific team id, while (1) is not. I was kind of dealing with this implicitly on the answers route by doing different access checks for writing team vs solving team users, and returning 403s for answers that a solving team hadn't gotten correct yet, but on second thought I think this is a bad approach... clients should never be returned 403s during normal operation.

I think (1) is (mostly) well modeled by the Answer resource introduced by this change. I do agree we should change it such that one puzzle can have multiple distinct answers (aka we shouldn't group all canonical answers together in a single list), and I think then we also need to change the Submission resource to model which of the puzzle's correct answers was submitted (which I think would have to be chosen by the call queue user, if we don't want to rely on fuzzy string matching to figure out which answer was supplied - although maybe we could make a human-overridable guess client-side in huntadmin to streamline the workflow, but now I'm getting too far off topic here...).

I think (2) would be better modeled as part of Visibility than as a separate Answer resource.

I'm thinking of handling (2) by adding a List<String> solvedAnswers field to Visibility, rather than encoding the set of solved answers inside of a VisibilityStatus. I expect that a hunt that supports partially-solved puzzles will add their own custom PARTIALLY_SOLVED states to the VisibilityStatusSet, but I don't think the set of answer strings themselves should be custom implemented per hunt.

Then we would simply not grant any access to Answer resources to solving teams at all.

Also, totally agreed that we should model puzzle/solvable and answer separately, and as full-fledged model objects. Modeling puzzle/solvable will be helpful for things like puzzle display names (as you mentioned) and maybe some kind of solvable grouping and/or tagging (we don't want the core to assume rounds, but it might be useful if the database had some limited awareness of structure/"some puzzles are more important than others" for dashboard purposes, although we could work around not having this). I'm not sure how I feel about a design where Solvable is a "base type" and Puzzle and Round are "types" of Solvables, need to think more about that... i guess if it's confined to within a hunt definition then it's OK.

I'll see if I have some time tomorrow to take a stab at revising this.

**Comment by tkfocht** [comment]
This looks right to me. The TODOs seem manageable.

We may want to have PuzzleResource be accessible to solving teams if there's metadata on the puzzles we want to have accessible. Puzzle name (separate from id) is a possibility for use on a log or overall status page for the team. Unlock metadata would also be useful for team retrieval if we think we might change it during the hunt and want it to change on its own in the display to teams. (This may be too much preplanning.) Basically, if we find a case, we'll do it.

**Comment by obijywk** [comment]
Cool, thanks TK. Should I merge this as-is, or any suggestions / cleanup you think we should take care of first?

**Comment by tkfocht** [comment]
I think just merge it as it is. In fact, I'll do it now.

**Pull request merged**
