### PR TITLE
Introduce strongly typed team properties

### PR DESCRIPTION
**Pull request by obijywk**

### CODE REVIEW

**Comment by tkfocht** [comment]
I don't grasp this one quite as fully. The Property class and the builder around it feel strange. I don't have a much better idea right now but I'd like to think about it a bit.

**Comment by obijywk** [comment]
OK, yeah, this one got kind of fancy implementation-wise, but from a huntimpl writer's perspective I think it should be pretty usable (given documentation and examples).

The class registration thing was my solution for enabling HuntStatusStore to find the classes for JSON deserialization, without having to store the entire fully-qualified class name in the database, or register them all with a @JsonSubTypes annotation on the base Property class (like we did for events) - I really want folks to be able to introduce new property classes without editing any of the core code. But maybe there's a better way!

Meditate on it, and let me know if you have any questions.

**Comment by tkfocht** [comment]
Can you check this into a remote branch on this repo so that it's easier for me to get and manipulate

**Comment by obijywk** [comment]
Sure.
https://github.com/eastern-toys/Cube/tree/teammodel
https://github.com/eastern-toys/Cube/commit/66ebfae21bf4a5110684c2b2dcdb38161951facc

**Comment by tkfocht** [comment]
I finally understood this by looking at the updated tests (which was lost in the noise until I got the code downloaded, so thanks for the checkin). This typing is much stronger than I had thought, but paradoxically somewhat less strong in that it all comes back to Property. It's an interesting pattern. Have you used it before?

Because the Property subclass is effectively both identifier and type, this means that if we have properties of the same base type (spoiler: we will) we will need to extend that type into identifier-level subclasses, correct? Is this a pattern you think we can effectively communicate to the future?

If my understanding here is correct, go ahead and commit.

**Comment by obijywk** [comment]
On Mon, Jun 6, 2016 at 1:48 AM, TK Focht <notifications@github.com> wrote:

> I finally understood this by looking at the updated tests (which was lost
> in the noise until I got the code downloaded, so thanks for the checkin).
> This typing is much stronger than I had thought, but paradoxically somewhat
> less strong in that it all comes back to Property.
>
I'd say the strength/safety comes from the precondition checks during Team
build (which unfortunately only happen at runtime, but so be it). After a
Team is built, access is quite safe when calling getTeamProperty (instead
of calling getTeamProperties and casting), which I'd strongly encourage.

I think this is the right place for the safety checks to be - we should
generally do the "scarier" stuff up front at JSON deserialization time, and
then use well-typed Java objects instead of Map<String, Object> throughout
all the business logic.

> It's an interesting pattern. Have you used it before?
>
I don't think I've used a pattern exactly like this before. It's a little
similar to what we did in the CompositeEventProcessor (since we're using
Class instances as "identifiers" and storing them in maps).

> Because the Property subclass is effectively both identifier and type,
> this means that if we have properties of the same base type (spoiler: we
> will) we will need to extend that type into identifier-level subclasses,
> correct? Is this a pattern you think we can effectively communicate to the
> future?
>
Are you suggesting there could be differently named team properties that
will have the same data structure and use the same Java class? I don't
think we should do that. Now that the properties are JSON objects instead
of Java basic types, we can nest lists and maps inside of them, which gives
us a lot of flexibility - I think I'd prefer a small number of complex
teamProperties to a large number of simple teamProperties. Not sure if that
covers the use case you're thinking of, but I suspect it could :-)

> If my understanding here is correct, go ahead and commit.
>
Thanks. I'll commit this as a starting point, and we can definitely iterate
on the design as needs arise.

**Pull request merged**
